os: windows
language: shell

env:
    global:
        - JAVA_HOME=$HOME/labsjdk-ce-11.0.5-jvmci-19.3-b06/
        - EXTRA_JAVA_HOMES=$HOME/openjdk1.8.0_232-jvmci-19.3-b06/
        - PATH=/c/Progra~2/Micros~1.0/VC/bin/amd64:${PATH}
        - PATH=$JAVA_HOME/bin:${PATH}
        - PATH=$HOME/mx:${PATH}
        - PATH=/c/python27:/c/python27/scripts:${PATH}
        
before_install:
    - cd $HOME
    
    #- wget --quiet https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-19.3-b06/openjdk-8u232-jvmci-19.3-b06-windows-amd64.tar.gz
    #- tar xf openjdk-8u232-jvmci-19.3-b06-windows-amd64.tar.gz
    #- echo --- Java 8 ---
    #- openjdk1.8.0_232-jvmci-19.3-b06/bin/java -Xmx32m -version
    #- openjdk1.8.0_232-jvmci-19.3-b06/bin/javac -J-Xmx32m -version
    #- echo ---
    
    #- wget --quiet https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-19.3-b06/labsjdk-ce-11.0.5+10-jvmci-19.3-b06-windows-amd64.tar.gz
    #- tar xf labsjdk-ce-11.0.5+10-jvmci-19.3-b06-windows-amd64.tar.gz
    #- echo --- Java 11 ---
    #- java -Xmx32m -version
    #- javac -J-Xmx32m -version
    #- echo ---
    
    - cd $TRAVIS_BUILD_DIR

install:
    - choco upgrade python2 -y --no-progress
    - where python

script:
    - which --all bash
    - ls -alh $PROGRAMFILES
    - ls -alh $PROGRAMFILES(X86)
    - python --version
    #- java --version
    #- cl -Bv
    #- env

